# Copyright 2019 Ole Kliemann, Malte Kliemann
#
# This file is part of DrMock.
#
# DrMock is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DrMock is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DrMock.  If not, see <https://www.gnu.org/licenses/>.

""" Makeshift tests for:

* mocker.Method.from_cursor
* mocker.Type.from_spelling
"""

from mocker import parse
from mocker.parse import Type
parse.configure("c++17")
import unittest

class TestType(unittest.TestCase):
    def test_from_cursor(self):
        # Retrieve two dictionaries from the cursor `root`:

        # * `parameter_types` maps a function's name (from
        #     "../resources/TestTypes.h") to the type of its only parameter.
        # * `return_types` maps a function's name (from
        #     "../resources/TestTypes.h") to the type of its return value.
        #
        # The expected data may be found at the end of the file.
        parameter_types = dict()
        return_types = dict()
        with open("resources/TestType.h", "r") as file:
            source = file.read()
        tu = parse.translate("resources/TestType.h", source)
        hf = parse.CppFile.from_unit(tu)
        cls = hf.get_class("IExample")
        funcs = [f for f in cls.public]
        for f in funcs:
            name = f.name
            if name in expected_parameter_types:
                type = str(f.parameters.pop())
                parameter_types.update({name: type})
            elif name in expected_return_types:
                type = str(f.return_type)
                return_types.update({name: type})

        # Check that the types are as expected.
        for method_name, expected in expected_parameter_types.items():
            type = parameter_types[method_name]
            with self.subTest(type = type, expected = expected):
                self.assertEqual(type, expected)
        for method_name, expected in expected_return_types.items():
            type = return_types[method_name]
            with self.subTest(type = type, expected = expected):
                self.assertEqual(type, expected)
        # Check that all tests are done.
        self.assertEqual(parameter_types, expected_parameter_types)
        self.assertEqual(return_types, expected_return_types)

    def test_decayed(self):
        tests = {
            ("T", "T"),
            ("T &", "T"),
            ("T &&", "T"),
            ("const T", "T"),
            ("const T &", "T"),
            ("T *", "T *"),
            ("T * const", "T *"),
            ("const T *", "const T *"),
            ("T * const &", "T *"),
            ("T * &&", "T *"),
            ("std::vector<T &>", "std::vector<T &>")
        }
        for spelling, expected in tests:
            with self.subTest(spelling = spelling, expected = expected):
                self.assertEqual(
                    Type.from_spelling(spelling).decayed(),
                    Type.from_spelling(expected)
                )

expected_parameter_types = {
    "func": "T",
    "funcConstLeft": "const T",
    "funcVolatileLeft": "volatile T",
    "funcConstVolatileLeft": "const volatile T",
    "funcVolatileConstLeft": "const volatile T",
    "funcConstRight": "const T",
    "funcVolatileRight": "volatile T",
    "funcConstVolatileRight": "const volatile T",
    "funcVolatileConstRight": "const volatile T",
    "funcConstLeftVolatileRight": "const volatile T",
    "funcVolatileLeftConstRight": "const volatile T",
    "funcPointer": "T *",
    "funcPointerToConstLeft": "const T *",
    "funcPointerToVolatileLeft": "volatile T *",
    "funcPointerToConstVolatileLeft": "const volatile T *",
    "funcPointerToVolatileConstLeft": "const volatile T *",
    "funcPointerToConstRight": "const T *",
    "funcPointerToVolatileRight": "volatile T *",
    "funcPointerToConstVolatileRight": "const volatile T *",
    "funcPointerToVolatileConstRight": "const volatile T *",
    "funcPointerToConstLeftVolatileRight": "const volatile T *",
    "funcPointerToVolatileLeftConstRight": "const volatile T *",
    "funcConstPointer": "T * const",
    "funcConstPointerToConstLeft": "const T * const",
    "funcConstPointerToVolatileLeft": "volatile T * const",
    "funcConstPointerToConstVolatileLeft": "const volatile T * const",
    "funcConstPointerToVolatileConstLeft": "const volatile T * const",
    "funcConstPointerToConstRight": "const T * const",
    "funcConstPointerToVolatileRight": "volatile T * const",
    "funcConstPointerToConstVolatileRight": "const volatile T * const",
    "funcConstPointerToVolatileConstRight": "const volatile T * const",
    "funcConstPointerToConstLeftVolatileRight": "const volatile T * const",
    "funcConstPointerToVolatileLeftConstRight": "const volatile T * const",
    "funcVolatilePointerToConstLeft": "const T * volatile",
    "funcVolatilePointerToVolatileLeft": "volatile T * volatile",
    "funcVolatilePointerToConstVolatileLeft": "const volatile T * volatile",
    "funcVolatilePointerToVolatileConstLeft": "const volatile T * volatile",
    "funcVolatilePointerToConstRight": "const T * volatile",
    "funcVolatilePointerToVolatileRight": "volatile T * volatile",
    "funcVolatilePointerToConstVolatileRight": "const volatile T * volatile",
    "funcVolatilePointerToVolatileConstRight": "const volatile T * volatile",
    "funcVolatilePointerToConstLeftVolatileRight": "const volatile T * volatile",
    "funcVolatilePointerToVolatileLeftConstRight": "const volatile T * volatile",
    "funcConstVolatilePointerToConstLeft": "const T * const volatile",
    "funcConstVolatilePointerToVolatileLeft": "volatile T * const volatile",
    "funcConstVolatilePointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcConstVolatilePointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcConstVolatilePointerToConstRight": "const T * const volatile",
    "funcConstVolatilePointerToVolatileRight": "volatile T * const volatile",
    "funcConstVolatilePointerToConstVolatileRight": "const volatile T * const volatile",
    "funcConstVolatilePointerToVolatileConstRight": "const volatile T * const volatile",
    "funcConstVolatilePointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcConstVolatilePointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcVolatileConstPointer": "T * const volatile",
    "funcVolatileConstPointerToConstLeft": "const T * const volatile",
    "funcVolatileConstPointerToVolatileLeft": "volatile T * const volatile",
    "funcVolatileConstPointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcVolatileConstPointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcVolatileConstPointerToConstRight": "const T * const volatile",
    "funcVolatileConstPointerToVolatileRight": "volatile T * const volatile",
    "funcVolatileConstPointerToConstVolatileRight": "const volatile T * const volatile",
    "funcVolatileConstPointerToVolatileConstRight": "const volatile T * const volatile",
    "funcVolatileConstPointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcVolatileConstPointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcReference": "T &",
    "funcReferenceToConstLeft": "const T &",
    "funcReferenceToVolatileLeft": "volatile T &",
    "funcReferenceToConstVolatileLeft": "const volatile T &",
    "funcReferenceToVolatileConstLeft": "const volatile T &",
    "funcReferenceToConstRight": "const T &",
    "funcReferenceToVolatileRight": "volatile T &",
    "funcReferenceToConstVolatileRight": "const volatile T &",
    "funcReferenceToVolatileConstRight": "const volatile T &",
    "funcReferenceToConstLeftVolatileRight": "const volatile T &",
    "funcReferenceToVolatileLeftConstRight": "const volatile T &",
    "funcRvalueReference": "T &&",
    "funcRvalueReferenceToConstLeft": "const T &&",
    "funcRvalueReferenceToVolatileLeft": "volatile T &&",
    "funcRvalueReferenceToConstVolatileLeft": "const volatile T &&",
    "funcRvalueReferenceToVolatileConstLeft": "const volatile T &&",
    "funcRvalueReferenceToConstRight": "const T &&",
    "funcRvalueReferenceToVolatileRight": "volatile T &&",
    "funcRvalueReferenceToConstVolatileRight": "const volatile T &&",
    "funcRvalueReferenceToVolatileConstRight": "const volatile T &&",
    "funcRvalueReferenceToConstLeftVolatileRight": "const volatile T &&",

    "funcPack": "Ts ...",
    "funcPackConstLeft": "const Ts ...",
    "funcPackVolatileLeft": "volatile Ts ...",
    "funcPackConstVolatileLeft": "const volatile Ts ...",
    "funcPackVolatileConstLeft": "const volatile Ts ...",
    "funcPackConstRight": "const Ts ...",
    "funcPackVolatileRight": "volatile Ts ...",
    "funcPackConstVolatileRight": "const volatile Ts ...",
    "funcPackVolatileConstRight": "const volatile Ts ...",
    "funcPackConstLeftVolatileRight": "const volatile Ts ...",
    "funcPackVolatileLeftConstRight": "const volatile Ts ...",
    "funcPackPointer": "Ts * ...",
    "funcPackPointerToConstLeft": "const Ts * ...",
    "funcPackPointerToVolatileLeft": "volatile Ts * ...",
    "funcPackPointerToConstVolatileLeft": "const volatile Ts * ...",
    "funcPackPointerToVolatileConstLeft": "const volatile Ts * ...",
    "funcPackPointerToConstRight": "const Ts * ...",
    "funcPackPointerToVolatileRight": "volatile Ts * ...",
    "funcPackPointerToConstVolatileRight": "const volatile Ts * ...",
    "funcPackPointerToVolatileConstRight": "const volatile Ts * ...",
    "funcPackPointerToConstLeftVolatileRight": "const volatile Ts * ...",
    "funcPackPointerToVolatileLeftConstRight": "const volatile Ts * ...",
    "funcPackConstPointer": "Ts * const ...",
    "funcPackConstPointerToConstLeft": "const Ts * const ...",
    "funcPackConstPointerToVolatileLeft": "volatile Ts * const ...",
    "funcPackConstPointerToConstVolatileLeft": "const volatile Ts * const ...",
    "funcPackConstPointerToVolatileConstLeft": "const volatile Ts * const ...",
    "funcPackConstPointerToConstRight": "const Ts * const ...",
    "funcPackConstPointerToVolatileRight": "volatile Ts * const ...",
    "funcPackConstPointerToConstVolatileRight": "const volatile Ts * const ...",
    "funcPackConstPointerToVolatileConstRight": "const volatile Ts * const ...",
    "funcPackConstPointerToConstLeftVolatileRight": "const volatile Ts * const ...",
    "funcPackConstPointerToVolatileLeftConstRight": "const volatile Ts * const ...",
    "funcPackVolatilePointerToConstLeft": "const Ts * volatile ...",
    "funcPackVolatilePointerToVolatileLeft": "volatile Ts * volatile ...",
    "funcPackVolatilePointerToConstVolatileLeft": "const volatile Ts * volatile ...",
    "funcPackVolatilePointerToVolatileConstLeft": "const volatile Ts * volatile ...",
    "funcPackVolatilePointerToConstRight": "const Ts * volatile ...",
    "funcPackVolatilePointerToVolatileRight": "volatile Ts * volatile ...",
    "funcPackVolatilePointerToConstVolatileRight": "const volatile Ts * volatile ...",
    "funcPackVolatilePointerToVolatileConstRight": "const volatile Ts * volatile ...",
    "funcPackVolatilePointerToConstLeftVolatileRight": "const volatile Ts * volatile ...",
    "funcPackVolatilePointerToVolatileLeftConstRight": "const volatile Ts * volatile ...",
    "funcPackConstVolatilePointerToConstLeft": "const Ts * const volatile ...",
    "funcPackConstVolatilePointerToVolatileLeft": "volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToConstVolatileLeft": "const volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToVolatileConstLeft": "const volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToConstRight": "const Ts * const volatile ...",
    "funcPackConstVolatilePointerToVolatileRight": "volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToConstVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToVolatileConstRight": "const volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToConstLeftVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackConstVolatilePointerToVolatileLeftConstRight": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointer": "Ts * const volatile ...",
    "funcPackVolatileConstPointerToConstLeft": "const Ts * const volatile ...",
    "funcPackVolatileConstPointerToVolatileLeft": "volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToConstVolatileLeft": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToVolatileConstLeft": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToConstRight": "const Ts * const volatile ...",
    "funcPackVolatileConstPointerToVolatileRight": "volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToConstVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToVolatileConstRight": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToConstLeftVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVolatileConstPointerToVolatileLeftConstRight": "const volatile Ts * const volatile ...",
    "funcPackReference": "Ts & ...",
    "funcPackReferenceToConstLeft": "const Ts & ...",
    "funcPackReferenceToVolatileLeft": "volatile Ts & ...",
    "funcPackReferenceToConstVolatileLeft": "const volatile Ts & ...",
    "funcPackReferenceToVolatileConstLeft": "const volatile Ts & ...",
    "funcPackReferenceToConstRight": "const Ts & ...",
    "funcPackReferenceToVolatileRight": "volatile Ts & ...",
    "funcPackReferenceToConstVolatileRight": "const volatile Ts & ...",
    "funcPackReferenceToVolatileConstRight": "const volatile Ts & ...",
    "funcPackReferenceToConstLeftVolatileRight": "const volatile Ts & ...",
    "funcPackReferenceToVolatileLeftConstRight": "const volatile Ts & ...",
    "funcPackRvalueReference": "Ts && ...",
    "funcPackRvalueReferenceToConstLeft": "const Ts && ...",
    "funcPackRvalueReferenceToVolatileLeft": "volatile Ts && ...",
    "funcPackRvalueReferenceToConstVolatileLeft": "const volatile Ts && ...",
    "funcPackRvalueReferenceToVolatileConstLeft": "const volatile Ts && ...",
    "funcPackRvalueReferenceToConstRight": "const Ts && ...",
    "funcPackRvalueReferenceToVolatileRight": "volatile Ts && ...",
    "funcPackRvalueReferenceToConstVolatileRight": "const volatile Ts && ...",
    "funcPackRvalueReferenceToVolatileConstRight": "const volatile Ts && ...",
    "funcPackRvalueReferenceToConstLeftVolatileRight": "const volatile Ts && ...",

    "funcVar": "T",
    "funcVarConstLeft": "const T",
    "funcVarVolatileLeft": "volatile T",
    "funcVarConstVolatileLeft": "const volatile T",
    "funcVarVolatileConstLeft": "const volatile T",
    "funcVarConstRight": "const T",
    "funcVarVolatileRight": "volatile T",
    "funcVarConstVolatileRight": "const volatile T",
    "funcVarVolatileConstRight": "const volatile T",
    "funcVarConstLeftVolatileRight": "const volatile T",
    "funcVarVolatileLeftConstRight": "const volatile T",
    "funcVarPointer": "T *",
    "funcVarPointerToConstLeft": "const T *",
    "funcVarPointerToVolatileLeft": "volatile T *",
    "funcVarPointerToConstVolatileLeft": "const volatile T *",
    "funcVarPointerToVolatileConstLeft": "const volatile T *",
    "funcVarPointerToConstRight": "const T *",
    "funcVarPointerToVolatileRight": "volatile T *",
    "funcVarPointerToConstVolatileRight": "const volatile T *",
    "funcVarPointerToVolatileConstRight": "const volatile T *",
    "funcVarPointerToConstLeftVolatileRight": "const volatile T *",
    "funcVarPointerToVolatileLeftConstRight": "const volatile T *",
    "funcVarConstPointer": "T * const",
    "funcVarConstPointerToConstLeft": "const T * const",
    "funcVarConstPointerToVolatileLeft": "volatile T * const",
    "funcVarConstPointerToConstVolatileLeft": "const volatile T * const",
    "funcVarConstPointerToVolatileConstLeft": "const volatile T * const",
    "funcVarConstPointerToConstRight": "const T * const",
    "funcVarConstPointerToVolatileRight": "volatile T * const",
    "funcVarConstPointerToConstVolatileRight": "const volatile T * const",
    "funcVarConstPointerToVolatileConstRight": "const volatile T * const",
    "funcVarConstPointerToConstLeftVolatileRight": "const volatile T * const",
    "funcVarConstPointerToVolatileLeftConstRight": "const volatile T * const",
    "funcVarVolatilePointerToConstLeft": "const T * volatile",
    "funcVarVolatilePointerToVolatileLeft": "volatile T * volatile",
    "funcVarVolatilePointerToConstVolatileLeft": "const volatile T * volatile",
    "funcVarVolatilePointerToVolatileConstLeft": "const volatile T * volatile",
    "funcVarVolatilePointerToConstRight": "const T * volatile",
    "funcVarVolatilePointerToVolatileRight": "volatile T * volatile",
    "funcVarVolatilePointerToConstVolatileRight": "const volatile T * volatile",
    "funcVarVolatilePointerToVolatileConstRight": "const volatile T * volatile",
    "funcVarVolatilePointerToConstLeftVolatileRight": "const volatile T * volatile",
    "funcVarVolatilePointerToVolatileLeftConstRight": "const volatile T * volatile",
    "funcVarConstVolatilePointerToConstLeft": "const T * const volatile",
    "funcVarConstVolatilePointerToVolatileLeft": "volatile T * const volatile",
    "funcVarConstVolatilePointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcVarConstVolatilePointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcVarConstVolatilePointerToConstRight": "const T * const volatile",
    "funcVarConstVolatilePointerToVolatileRight": "volatile T * const volatile",
    "funcVarConstVolatilePointerToConstVolatileRight": "const volatile T * const volatile",
    "funcVarConstVolatilePointerToVolatileConstRight": "const volatile T * const volatile",
    "funcVarConstVolatilePointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcVarConstVolatilePointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcVarVolatileConstPointer": "T * const volatile",
    "funcVarVolatileConstPointerToConstLeft": "const T * const volatile",
    "funcVarVolatileConstPointerToVolatileLeft": "volatile T * const volatile",
    "funcVarVolatileConstPointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcVarVolatileConstPointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcVarVolatileConstPointerToConstRight": "const T * const volatile",
    "funcVarVolatileConstPointerToVolatileRight": "volatile T * const volatile",
    "funcVarVolatileConstPointerToConstVolatileRight": "const volatile T * const volatile",
    "funcVarVolatileConstPointerToVolatileConstRight": "const volatile T * const volatile",
    "funcVarVolatileConstPointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcVarVolatileConstPointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcVarReference": "T &",
    "funcVarReferenceToConstLeft": "const T &",
    "funcVarReferenceToVolatileLeft": "volatile T &",
    "funcVarReferenceToConstVolatileLeft": "const volatile T &",
    "funcVarReferenceToVolatileConstLeft": "const volatile T &",
    "funcVarReferenceToConstRight": "const T &",
    "funcVarReferenceToVolatileRight": "volatile T &",
    "funcVarReferenceToConstVolatileRight": "const volatile T &",
    "funcVarReferenceToVolatileConstRight": "const volatile T &",
    "funcVarReferenceToConstLeftVolatileRight": "const volatile T &",
    "funcVarReferenceToVolatileLeftConstRight": "const volatile T &",
    "funcVarRvalueReference": "T &&",
    "funcVarRvalueReferenceToConstLeft": "const T &&",
    "funcVarRvalueReferenceToVolatileLeft": "volatile T &&",
    "funcVarRvalueReferenceToConstVolatileLeft": "const volatile T &&",
    "funcVarRvalueReferenceToVolatileConstLeft": "const volatile T &&",
    "funcVarRvalueReferenceToConstRight": "const T &&",
    "funcVarRvalueReferenceToVolatileRight": "volatile T &&",
    "funcVarRvalueReferenceToConstVolatileRight": "const volatile T &&",
    "funcVarRvalueReferenceToVolatileConstRight": "const volatile T &&",
    "funcVarRvalueReferenceToConstLeftVolatileRight": "const volatile T &&",

    "funcPackVar": "Ts ...",
    "funcPackVarConstLeft": "const Ts ...",
    "funcPackVarVolatileLeft": "volatile Ts ...",
    "funcPackVarConstVolatileLeft": "const volatile Ts ...",
    "funcPackVarVolatileConstLeft": "const volatile Ts ...",
    "funcPackVarConstRight": "const Ts ...",
    "funcPackVarVolatileRight": "volatile Ts ...",
    "funcPackVarConstVolatileRight": "const volatile Ts ...",
    "funcPackVarVolatileConstRight": "const volatile Ts ...",
    "funcPackVarConstLeftVolatileRight": "const volatile Ts ...",
    "funcPackVarVolatileLeftConstRight": "const volatile Ts ...",
    "funcPackVarPointer": "Ts * ...",
    "funcPackVarPointerToConstLeft": "const Ts * ...",
    "funcPackVarPointerToVolatileLeft": "volatile Ts * ...",
    "funcPackVarPointerToConstVolatileLeft": "const volatile Ts * ...",
    "funcPackVarPointerToVolatileConstLeft": "const volatile Ts * ...",
    "funcPackVarPointerToConstRight": "const Ts * ...",
    "funcPackVarPointerToVolatileRight": "volatile Ts * ...",
    "funcPackVarPointerToConstVolatileRight": "const volatile Ts * ...",
    "funcPackVarPointerToVolatileConstRight": "const volatile Ts * ...",
    "funcPackVarPointerToConstLeftVolatileRight": "const volatile Ts * ...",
    "funcPackVarPointerToVolatileLeftConstRight": "const volatile Ts * ...",
    "funcPackVarConstPointer": "Ts * const ...",
    "funcPackVarConstPointerToConstLeft": "const Ts * const ...",
    "funcPackVarConstPointerToVolatileLeft": "volatile Ts * const ...",
    "funcPackVarConstPointerToConstVolatileLeft": "const volatile Ts * const ...",
    "funcPackVarConstPointerToVolatileConstLeft": "const volatile Ts * const ...",
    "funcPackVarConstPointerToConstRight": "const Ts * const ...",
    "funcPackVarConstPointerToVolatileRight": "volatile Ts * const ...",
    "funcPackVarConstPointerToConstVolatileRight": "const volatile Ts * const ...",
    "funcPackVarConstPointerToVolatileConstRight": "const volatile Ts * const ...",
    "funcPackVarConstPointerToConstLeftVolatileRight": "const volatile Ts * const ...",
    "funcPackVarConstPointerToVolatileLeftConstRight": "const volatile Ts * const ...",
    "funcPackVarVolatilePointerToConstLeft": "const Ts * volatile ...",
    "funcPackVarVolatilePointerToVolatileLeft": "volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToConstVolatileLeft": "const volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToVolatileConstLeft": "const volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToConstRight": "const Ts * volatile ...",
    "funcPackVarVolatilePointerToVolatileRight": "volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToConstVolatileRight": "const volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToVolatileConstRight": "const volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToConstLeftVolatileRight": "const volatile Ts * volatile ...",
    "funcPackVarVolatilePointerToVolatileLeftConstRight": "const volatile Ts * volatile ...",
    "funcPackVarConstVolatilePointerToConstLeft": "const Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToVolatileLeft": "volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToConstVolatileLeft": "const volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToVolatileConstLeft": "const volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToConstRight": "const Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToVolatileRight": "volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToConstVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToVolatileConstRight": "const volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToConstLeftVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVarConstVolatilePointerToVolatileLeftConstRight": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointer": "Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToConstLeft": "const Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToVolatileLeft": "volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToConstVolatileLeft": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToVolatileConstLeft": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToConstRight": "const Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToVolatileRight": "volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToConstVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToVolatileConstRight": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToConstLeftVolatileRight": "const volatile Ts * const volatile ...",
    "funcPackVarVolatileConstPointerToVolatileLeftConstRight": "const volatile Ts * const volatile ...",
    "funcPackVarReference": "Ts & ...",
    "funcPackVarReferenceToConstLeft": "const Ts & ...",
    "funcPackVarReferenceToVolatileLeft": "volatile Ts & ...",
    "funcPackVarReferenceToConstVolatileLeft": "const volatile Ts & ...",
    "funcPackVarReferenceToVolatileConstLeft": "const volatile Ts & ...",
    "funcPackVarReferenceToConstRight": "const Ts & ...",
    "funcPackVarReferenceToVolatileRight": "volatile Ts & ...",
    "funcPackVarReferenceToConstVolatileRight": "const volatile Ts & ...",
    "funcPackVarReferenceToVolatileConstRight": "const volatile Ts & ...",
    "funcPackVarReferenceToConstLeftVolatileRight": "const volatile Ts & ...",
    "funcPackVarReferenceToVolatileLeftConstRight": "const volatile Ts & ...",
    "funcPackVarRvalueReference": "Ts && ...",
    "funcPackVarRvalueReferenceToConstLeft": "const Ts && ...",
    "funcPackVarRvalueReferenceToVolatileLeft": "volatile Ts && ...",
    "funcPackVarRvalueReferenceToConstVolatileLeft": "const volatile Ts && ...",
    "funcPackVarRvalueReferenceToVolatileConstLeft": "const volatile Ts && ...",
    "funcPackVarRvalueReferenceToConstRight": "const Ts && ...",
    "funcPackVarRvalueReferenceToVolatileRight": "volatile Ts && ...",
    "funcPackVarRvalueReferenceToConstVolatileRight": "const volatile Ts && ...",
    "funcPackVarRvalueReferenceToVolatileConstRight": "const volatile Ts && ...",
    "funcPackVarRvalueReferenceToConstLeftVolatileRight": "const volatile Ts && ...",
}
expected_return_types = {
    "funcReturn": "T",
    "funcReturnConstLeft": "const T",
    "funcReturnVolatileLeft": "volatile T",
    "funcReturnConstVolatileLeft": "const volatile T",
    "funcReturnVolatileConstLeft": "const volatile T",
    "funcReturnConstRight": "const T",
    "funcReturnVolatileRight": "volatile T",
    "funcReturnConstVolatileRight": "const volatile T",
    "funcReturnVolatileConstRight": "const volatile T",
    "funcReturnConstLeftVolatileRight": "const volatile T",
    "funcReturnVolatileLeftConstRight": "const volatile T",
    "funcReturnPointer": "T *",
    "funcReturnPointerToConstLeft": "const T *",
    "funcReturnPointerToVolatileLeft": "volatile T *",
    "funcReturnPointerToConstVolatileLeft": "const volatile T *",
    "funcReturnPointerToVolatileConstLeft": "const volatile T *",
    "funcReturnPointerToConstRight": "const T *",
    "funcReturnPointerToVolatileRight": "volatile T *",
    "funcReturnPointerToConstVolatileRight": "const volatile T *",
    "funcReturnPointerToVolatileConstRight": "const volatile T *",
    "funcReturnPointerToConstLeftVolatileRight": "const volatile T *",
    "funcReturnPointerToVolatileLeftConstRight": "const volatile T *",
    "funcReturnConstPointer": "T * const",
    "funcReturnConstPointerToConstLeft": "const T * const",
    "funcReturnConstPointerToVolatileLeft": "volatile T * const",
    "funcReturnConstPointerToConstVolatileLeft": "const volatile T * const",
    "funcReturnConstPointerToVolatileConstLeft": "const volatile T * const",
    "funcReturnConstPointerToConstRight": "const T * const",
    "funcReturnConstPointerToVolatileRight": "volatile T * const",
    "funcReturnConstPointerToConstVolatileRight": "const volatile T * const",
    "funcReturnConstPointerToVolatileConstRight": "const volatile T * const",
    "funcReturnConstPointerToConstLeftVolatileRight": "const volatile T * const",
    "funcReturnConstPointerToVolatileLeftConstRight": "const volatile T * const",
    "funcReturnVolatilePointerToConstLeft": "const T * volatile",
    "funcReturnVolatilePointerToVolatileLeft": "volatile T * volatile",
    "funcReturnVolatilePointerToConstVolatileLeft": "const volatile T * volatile",
    "funcReturnVolatilePointerToVolatileConstLeft": "const volatile T * volatile",
    "funcReturnVolatilePointerToConstRight": "const T * volatile",
    "funcReturnVolatilePointerToVolatileRight": "volatile T * volatile",
    "funcReturnVolatilePointerToConstVolatileRight": "const volatile T * volatile",
    "funcReturnVolatilePointerToVolatileConstRight": "const volatile T * volatile",
    "funcReturnVolatilePointerToConstLeftVolatileRight": "const volatile T * volatile",
    "funcReturnVolatilePointerToVolatileLeftConstRight": "const volatile T * volatile",
    "funcReturnConstVolatilePointerToConstLeft": "const T * const volatile",
    "funcReturnConstVolatilePointerToVolatileLeft": "volatile T * const volatile",
    "funcReturnConstVolatilePointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcReturnConstVolatilePointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcReturnConstVolatilePointerToConstRight": "const T * const volatile",
    "funcReturnConstVolatilePointerToVolatileRight": "volatile T * const volatile",
    "funcReturnConstVolatilePointerToConstVolatileRight": "const volatile T * const volatile",
    "funcReturnConstVolatilePointerToVolatileConstRight": "const volatile T * const volatile",
    "funcReturnConstVolatilePointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcReturnConstVolatilePointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcReturnVolatileConstPointer": "T * const volatile",
    "funcReturnVolatileConstPointerToConstLeft": "const T * const volatile",
    "funcReturnVolatileConstPointerToVolatileLeft": "volatile T * const volatile",
    "funcReturnVolatileConstPointerToConstVolatileLeft": "const volatile T * const volatile",
    "funcReturnVolatileConstPointerToVolatileConstLeft": "const volatile T * const volatile",
    "funcReturnVolatileConstPointerToConstRight": "const T * const volatile",
    "funcReturnVolatileConstPointerToVolatileRight": "volatile T * const volatile",
    "funcReturnVolatileConstPointerToConstVolatileRight": "const volatile T * const volatile",
    "funcReturnVolatileConstPointerToVolatileConstRight": "const volatile T * const volatile",
    "funcReturnVolatileConstPointerToConstLeftVolatileRight": "const volatile T * const volatile",
    "funcReturnVolatileConstPointerToVolatileLeftConstRight": "const volatile T * const volatile",
    "funcReturnReference": "T &",
    "funcReturnReferenceToConstLeft": "const T &",
    "funcReturnReferenceToVolatileLeft": "volatile T &",
    "funcReturnReferenceToConstVolatileLeft": "const volatile T &",
    "funcReturnReferenceToVolatileConstLeft": "const volatile T &",
    "funcReturnReferenceToConstRight": "const T &",
    "funcReturnReferenceToVolatileRight": "volatile T &",
    "funcReturnReferenceToConstVolatileRight": "const volatile T &",
    "funcReturnReferenceToVolatileConstRight": "const volatile T &",
    "funcReturnReferenceToConstLeftVolatileRight": "const volatile T &",
    "funcReturnReferenceToVolatileLeftConstRight": "const volatile T &",
    "funcReturnRvalueReference": "T &&",
    "funcReturnRvalueReferenceToConstLeft": "const T &&",
    "funcReturnRvalueReferenceToVolatileLeft": "volatile T &&",
    "funcReturnRvalueReferenceToConstVolatileLeft": "const volatile T &&",
    "funcReturnRvalueReferenceToVolatileConstLeft": "const volatile T &&",
    "funcReturnRvalueReferenceToConstRight": "const T &&",
    "funcReturnRvalueReferenceToVolatileRight": "volatile T &&",
    "funcReturnRvalueReferenceToConstVolatileRight": "const volatile T &&",
    "funcReturnRvalueReferenceToVolatileConstRight": "const volatile T &&",
    "funcReturnRvalueReferenceToConstLeftVolatileRight": "const volatile T &&",
}
