name: Windows (install, test)
on:
  push:
    branches:
    - master
    - develop
    - rc-0.6
  pull_request:
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jurplel/install-qt-action@v2
      - uses: lukka/get-cmake@latest
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h
      - name: Install libclang
        run: choco install llvm
      - name: Install drmock-generator
        run: pip install drmock-generator
      - name: Compile drmock
        run: |
          cmake . -DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=$Qt5_Dir
          make
          ctest --output-on-failure
        env:
          DRMOCK_QT_PATH: $Qt5_Dir
